version: '3'

services:
  alarm-server:
    image: alarm-server
    container_name: alarm-server
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    networks:
      - server-net

networks:
  server-net:
    driver: bridge
    name: alarm-server-net
