version: '3'

services:
  alarm-server:
    image: alarm-server
    container_name: alarm-server
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    networks:
      - alarm-net

networks:
  alarm-net:
    driver: bridge
    name: alarm-net

    